spring:
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true # 404交给异常处理器处理
  datasource:
    url: jdbc:mysql://localhost:3306/zk
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver